/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
    './pages/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed': '#9cf0ff',
        'on-secondary-container': '#abb5cb',
        'on-primary-container': '#5b0011',
        'surface': '#0d131f',
        'on-tertiary-container': '#002f35',
        'surface-bright': '#333946',
        'on-tertiary-fixed-variant': '#004f58',
        'background': '#0d131f',
        'on-surface-variant': '#e3bebd',
        'primary-fixed-dim': '#ffb3b3',
        'secondary-container': '#3d4759',
        'outline-variant': '#5b4040',
        'inverse-surface': '#dde2f3',
        'error-container': '#93000a',
        'primary': '#ffb3b3',
        'secondary-fixed-dim': '#bdc7dc',
        'surface-container-lowest': '#080e1a',
        'inverse-primary': '#bb1332',
        'outline': '#aa8988',
        'inverse-on-surface': '#2a303d',
        'on-secondary': '#273141',
        'on-error': '#690005',
        'on-tertiary': '#00363d',
        'tertiary-container': '#009fb2',
        'tertiary-fixed-dim': '#00daf3',
        'surface-dim': '#0d131f',
        'tertiary': '#00daf3',
        'on-primary-fixed-variant': '#920021',
        'on-secondary-fixed-variant': '#3d4759',
        'on-primary-fixed': '#400009',
        'secondary': '#bdc7dc',
        'surface-container-low': '#161c27',
        'on-background': '#dde2f3',
        'surface-container-high': '#242a36',
        'error': '#ffb4ab',
        'primary-fixed': '#ffdad9',
        'primary-container': '#ff5260',
        'on-error-container': '#ffdad6',
        'surface-container-highest': '#2f3542',
        'surface-variant': '#2f3542',
        'on-primary': '#680015',
        'on-surface': '#dde2f3',
        'surface-tint': '#ffb3b3',
        'surface-container': '#1a202c',
        'on-secondary-fixed': '#121c2c',
        'on-tertiary-fixed': '#001f24',
        'secondary-fixed': '#d9e3f9',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '1rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
